import type { CandidateFacts } from './inference-engine';

export interface MockCandidate {
  id: string;
  facts: CandidateFacts;
  tanggal: string;
}

export const MOCK_CANDIDATES: MockCandidate[] = [
  {
    id: 'cand-001',
    tanggal: '2026-06-07',
    facts: {
      nama: 'Rina Kusuma',
      jarak_rumah_km: 5,
      memiliki_kendaraan: 'ya',
      akses_transportasi: 'mudah',
      mobilitas_malam: 'bebas',
      shift_malam: 'tidak',
      faktor_keamanan: 'tidak',
      kemampuan_masak: 'cukup',
      fisik_kuat: 'tidak',
      pengalaman_fnb_tahun: 3,
      riwayat_kerja_bulan: 18,
      lulus_administrasi: 'ya',
      sikap_ramah: 'baik',
      hadir_interview: 'tepat_waktu',
      disiplin: 'tinggi',
      teamwork: 'baik',
      panik_saat_tekanan: 'tidak',
      mood: 'stabil',
      kemampuan_individu: 'baik',
      lulus_wawancara: 'ya',
      hasil_trial: 'baik',
    },
  },
  {
    id: 'cand-002',
    tanggal: '2026-06-07',
    facts: {
      nama: 'Budi Santoso',
      jarak_rumah_km: 15,
      memiliki_kendaraan: 'tidak',
      akses_transportasi: 'sulit',
      mobilitas_malam: 'terbatas',
      shift_malam: 'ya',
      faktor_keamanan: 'perlu',
      kemampuan_masak: 'baik',
      fisik_kuat: 'ya',
      pengalaman_fnb_tahun: 1,
      riwayat_kerja_bulan: 2,
      lulus_administrasi: 'ya',
      sikap_ramah: 'cukup',
      hadir_interview: 'terlambat',
      disiplin: 'tinggi',
      teamwork: 'cukup',
      panik_saat_tekanan: 'tidak',
      mood: 'stabil',
      kemampuan_individu: 'baik',
      lulus_wawancara: 'ya',
      hasil_trial: 'cukup',
    },
  },
  {
    id: 'cand-003',
    tanggal: '2026-06-07',
    facts: {
      nama: 'Dewi Lestari',
      jarak_rumah_km: 8,
      memiliki_kendaraan: 'ya',
      akses_transportasi: 'mudah',
      mobilitas_malam: 'bebas',
      shift_malam: 'tidak',
      faktor_keamanan: 'tidak',
      kemampuan_masak: 'tidak',
      fisik_kuat: 'tidak',
      pengalaman_fnb_tahun: 0,
      riwayat_kerja_bulan: 1,
      lulus_administrasi: 'ya',
      sikap_ramah: 'baik',
      hadir_interview: 'tepat_waktu',
      disiplin: 'sedang',
      teamwork: 'rendah',
      panik_saat_tekanan: 'ya',
      mood: 'tidak_stabil',
      kemampuan_individu: 'baik',
      lulus_wawancara: 'tidak',
      hasil_trial: 'cukup',
    },
  },
];
